greetings = [
    "hi",
    "hello",
    "hey",
    "helloo",
    "hellooo",
    "g morining",
    "gmorning",
    "good morning",
    "morning",
    "good day",
    "good afternoon",
    "good evening",
    "greetings",
    "greeting",
    "good to see you",
    "its good seeing you",
    "how are you",
    "how're you",
    "how are you doing",
    "how ya doin'",
    "how ya doin",
    "how is everything",
    "how is everything going",
    "how's everything going",
    "how is you",
    "how's you",
    "how are things",
    "how're things",
    "how is it going",
    "how's it going",
    "how's it goin'",
    "how's it goin",
    "how is life been treating you",
    "how's life been treating you",
    "how have you been",
    "how've you been",
    "what is up",
    "what's up",
    "what is cracking",
    "what's cracking",
    "what is good",
    "what's good",
    "what is happening",
    "what's happening",
    "what is new",
    "what's new",
    "what is neww",
    "g’day",
    "howdy",
]

name_formatters = [
    "its {}",
    "{} here",
    "you've tuned into {} FM",
    "I'm {}",
    "I am {}",
    "you're reading {}",
    "look out, it's {}",
]

fact_adjectives = [
    "curious",
    "odd",
    "peculiar",
    "singular",
    "fishy",
    "shady",
    "suspicious",
    "amusing",
    "comic",
    "comical",
    "laughable",
    "mirthful",
    "chilling",
    "big",
    "heavy",
    "large",
    "outstanding",
    "bang-up",
    "corking",
    "cracking",
    "groovy",
    "neat",
    "nifty",
    "smashing",
    "excellent",
    "fantabulous",
    "first-class",
    "ripping",
    "glorious",
    "resplendent",
    "splendiferous",
    "brilliant",
    "magnificent",
    "silly",
]

pub_line_formatters = [
    "It's a {} day",
    "We should go to {}",
    "Can't wait to go to {}",
    "{} ?????????",
    "{}?",
    "I want to {}",
]
